version: '3'

services:
  algod:
    image: algorand/algod:master
    platform: linux/amd64
    ports:
      - "4001:8080" # algod
      - "4160:4160" # gossip
      - "9100:9100" # prometheus
    environment:
      - DEV_MODE=1
      - PROFILE=development
      - TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    healthcheck:
      test: curl -f http://localhost:8080/health
      interval: 2s
      retries: 30
