version: '3'

services:
  algod:
    image: wwinder/algod:latest
    ports:
      - "4001:8080" # algod
      - "4160:4160" # gossip
      - "9100:9100" # prometheus
    environment:
      - DEV_MODE
      - TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  # TODO: do not merge with this kmd service. This is only needed cause I don't want to
  # stand-up a seperate service locally
  kmd:
    image: makerxau/algorand-sandbox-dev:latest
    ports:
      - "4002:4002"
