name: Build and Unit Tests Template
on: workflow_call
jobs:
  my-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Step 1
        run: echo "Hello, world!"
      - name: Step 2
        run: echo "This is a template step."
