name: "Nightly Workflow"
on:
  schedule:
    - cron: "*/10 * * * *"

# permissions:
#   contents: write
#   pull-requests: write

jobs:
  hello2:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello there
        run: |
          echo "hello there"
          echo "goodbye"
