name: "Nightly Build"
on:
  pull_request:
  push:
    tags:
      - v**
    branches:
      - source-map-b1
  schedule:
    - cron: "57 0 * * *"

jobs:
  check-date:
    runs-on: ubuntu-20.04
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  build-test:
    needs: [check-date]
    if: ${{ github.event_name == 'release' || needs.check_date.outputs.WAS_EDITED == 'true' }}

    runs-on: ubuntu-20.04
    container: python:${{ matrix.python }}
    strategy:
      matrix:
        python: ["3.10", "3.11"]
    steps:
      - run: python3 --version
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install python dependencies
        run: make setup-development
      - name: Build and Unit Tests
        run: make lint-and-test
