name: "Nightly Build"
on:
  schedule:
    - cron: "25 * * * *"

jobs:
  check-date:
    runs-on: ubuntu-20.04
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  build-test:
    uses: ./.github/workflows/build.yml#build-test
    needs: [check-date]
    if: ${{ needs.check_date.outputs.WAS_EDITED == 'true' }}
